### PR TITLE
Update

### PR DESCRIPTION
**Pull request by gamersindo1223**

### CODE REVIEW

**Review by MoonLGH — CHANGES_REQUESTED** [review]
./data/current.json must be atleast an empty array, not a empty file

**Comment by MoonLGH** [comment]
also dont remove .gitignore and node_modules 💀

**Comment by gamersindo1223** [comment]
> also dont remove .gitignore and node_modules 💀

If you didnt remove it, the project size will be very large

**Comment by gamersindo1223** [comment]
Will fix tmrw

**Comment by gamersindo1223** [comment]
Will close temporarily, because too many bug

**Comment by MoonLGH** [comment]
> > also dont remove .gitignore and node_modules 💀
> 
> If you didnt remove it, the project size will be very large

I mean don't remove .gitignore, it has node_modules excepted to git in it

**Comment by gamersindo1223** [comment]
@MoonLGH could you make a new branch named fetch-code? Thanks

**Pull request closed without merging**
